spring:
  application:
    name: user-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/users
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: mysql
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081