package com.durgesh.user.dto;

public enum HotelStatus {
    PENDING_ACTIVATION,
    STATUS_VERIFIED,
    UNDER_CONSTRUCTION,
    COMING_SOON,
    SOFT_OPENING,
    OPEN,
    CLOSED,
    UNDER_RENOVATION,
    TEMPORARILY_CLOSED,
    PERMANENTLY_CLOSED,
    BOOKED_OUT
}